### ISSUE TITLE
php version error on Ch2 docker-compose.yml

### ISSUE THREAD

**Issue by jzedwards** [PacktPublishing/Modernizing-Enterprise-CMS-using-Pimcore#12]
running the install.sh for Ch2 (p35) gives error
```pimcore/pimcore[v11.0.4, ..., v11.0.6] require php ~8.1.0 || ~8.2.0 -> your php version (8.0.10) does not satisfy that requirement.```

appears current pimcore docker image requires 8.2 but Ch2 docker-compose.yml specifies pimcore/pimcore:PHP8.0-apache
doesn't look like there is a pimcore/pimcore 8.2 apache
docker-compose.yml requires update to correct apache image; failed with change to library/php:8.2-apache

will do a basic pimcore docker install from std gh repo for now
enjoying the book - thx - John

**Comment by zeppaman** [comment]
hello @jzedwards 
this is because, in the last few days, pimcore changed the main (default) version of pimcore, due to the release of Pimcore 11. So, now, if you do not specify anything the new installation using `COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/skeleton tmp` downloads the latest version, that's not compatible with the container specified in the docker composer.

The solution that works on my local is to simply specify the proper version into the composer command, for example adding 10.2 suffix:
`COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/skeleton:10.2 tmp`

This has to be done in all install.sh scripts of each chapter before installation.

**Comment by jzedwards** [comment]
thanks for update; back to learning today
